name: build ipyeos manylinux

on:
  push:
    # branches: [ main ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    env:
      IPYEOS_VERSION: 0.1.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
          fetch-depth: 0
      - name: Cache eos build
        uses: actions/cache@v2
        id: cache-eosio-build
        with:
          key: eosio-build-v2.1.0-manylinux
          path: eos/build
      - name: Build eos
        if: steps.cache-eosio-build.outputs.cache-hit != 'true'
        working-directory: eos
        run: ./scripts/eosio_build.sh -y
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3.7 -m pip install scikit-build cython auditwheel
          python3.8 -m pip install scikit-build cython auditwheel
          python3.9 -m pip install scikit-build cython auditwheel
          python3.10 -m pip install scikit-build cython auditwheel
      - name: call release.sh
        run: |
          ./release.sh
      - name: Build pyeos with python3.7
        run: |
          ln -sf /opt/python/cp37-cp37m/bin/cython /usr/local/bin/cython
          python3.7 setup.py sdist bdist_wheel
      - name: Build pyeos with python3.8
        run: |
          ln -sf /opt/python/cp38-cp38/bin/cython /usr/local/bin/cython
          python3.8 setup.py sdist bdist_wheel
      - name: Build pyeos with python3.9
        run: |
          ln -sf /opt/python/cp39-cp39/bin/cython /usr/local/bin/cython
          python3.9 setup.py sdist bdist_wheel
      - name: Build pyeos with python3.10
        run: |
          ln -sf /opt/python/cp310-cp310/bin/cython /usr/local/bin/cython
          python3.10 setup.py sdist bdist_wheel
      - name: run auditwheel
        working-directory: dist
        run: |
          python3.7 -m auditwheel repair --plat manylinux_2_17_x86_64 ipyeos-${{ env.IPYEOS_VERSION }}-cp37-cp37m-linux_x86_64.whl
          python3.8 -m auditwheel repair --plat manylinux_2_17_x86_64 ipyeos-${{ env.IPYEOS_VERSION }}-cp38-cp38-linux_x86_64.whl
          python3.9 -m auditwheel repair --plat manylinux_2_17_x86_64 ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-linux_x86_64.whl
          python3.10 -m auditwheel repair --plat manylinux_2_17_x86_64 ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-linux_x86_64.whl
      - name: release-pyeos
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
