name: build tinygo

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    env:
      PYEOS_VERSION: v0.1.6
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        # os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        # os: ['ubuntu-18.04', 'macos-latest']
        os: ['ubuntu-18.04']
      fail-fast: false
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 10
          platform: x64
      - name: clang version
        run: |
          clang --version
      - name: Install wget
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install wget --no-progress
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
          fetch-depth: 0
      - name: Cache eos build
        uses: actions/cache@v2
        id: cache-eosio-build
        with:
          key: ${{ matrix.os }}-eosio-build-v2.0.0
          path: eos/build
      - name: Build eos
        if: steps.cache-eosio-build.cache-hit != 'true'
        working-directory: eos
        run: ./scripts/eosio_build.sh -y
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest scikit-build cython auditwheel
      - name: Build pyeos
        run: |
          python setup.py sdist bdist_wheel
      - name: get whl file
        id: whlfile
        run: |
          echo "::set-output name=value::$(python scripts/get_whl_file.py)"
      - name: Install pyeos
        run: |
          python -m pip uninstall pyeos -y;python -m pip install ./dist/${{ steps.whlfile.outputs.value }}
      - name: release-pyeos
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/${{ steps.whlfile.outputs.value }}
