name: build ipyeos

on:
  push:
    branches: [ debug ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: 'macos-12'
    env:
      IPYEOS_VERSION: 0.4.3
      SYSTEM_VERSION_COMPAT: 0
      PREBUILD_BINARY_VERSION: v2.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
          fetch-depth: 0
      - name: download prebuild binarys
        run: |
          wget https://github.com/uuosio/leap/releases/download/${{ env.PREBUILD_BINARY_VERSION }}/release-macos.tar.gz
          tar -C pysrc -xf release-macos.tar.gz
          brew install llvm@11
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: build python3.8 wheel package
        run: |
          python3.8 -m pip install scikit-build cython
          CC=clang CXX=clang++ python3.8 setup.py sdist bdist_wheel --plat-name macosx-10.15-x86_64
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: build python3.9 wheel package
        run: |
          python3.9 -m pip install scikit-build cython
          CC=clang CXX=clang++ python3.9 setup.py sdist bdist_wheel --plat-name macosx-10.15-x86_64
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: build python3.10 wheel package
        run: |
          python3.10 -m pip install scikit-build cython
          CC=clang CXX=clang++ python3.10 setup.py sdist bdist_wheel --plat-name macosx-10.15-x86_64
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: build python3.11 wheel package
        run: |
          python3.11 -m pip install scikit-build cython
          CC=clang CXX=clang++ python3.11 setup.py sdist bdist_wheel --plat-name macosx-10.15-x86_64
      - name: get whl file
        id: whlfile
        run: |
          echo "::set-output name=value::$(python scripts/get_whl_file.py)"
      - name: Install ipyeos
        run: |
          ls ./dist
          python3.10 -m pip install ./dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-macosx_10_15_x86_64.whl
          eosdebugger &
          python3.10 -m ipyeos -m pytest -s -x tests/test.py
      - name: release-ipyeos
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-macosx_10_15_x86_64.whl
            ./dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp38-cp38-macosx_10_15_x86_64.whl
            ./dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-macosx_10_15_x86_64.whl
            ./dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp311-cp311-macosx_10_15_x86_64.whl
