name: build ipyeos manylinux

on:
  push:
    branches: [ debug ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-20.04
    # container:
    #   image: quay.io/pypa/manylinux2014_x86_64
    env:
      IPYEOS_VERSION: 0.3.5
      PREBUILD_BINARY_VERSION: v1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: download prebuild binarys
        run: |
          wget https://github.com/uuosio/leap/releases/download/${{ env.PREBUILD_BINARY_VERSION }}/release-linux.tar.gz
          tar -C pysrc -xf release-linux.tar.gz
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: build python3.8 wheel package
        run: |
          python3.8 -m pip install scikit-build cython auditwheel
          python3.8 setup.py sdist bdist_wheel
          python3.8 -m auditwheel repair --plat manylinux_2_31_x86_64 dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp38-cp38-linux_x86_64.whl
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: build python3.9 wheel package
        run: |
          python3.9 -m pip install scikit-build cython auditwheel
          python3.9 setup.py sdist bdist_wheel
          python3.9 -m auditwheel repair --plat manylinux_2_31_x86_64 dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-linux_x86_64.whl
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: build python3.10 wheel package
        run: |
          python3.10 -m pip install scikit-build cython auditwheel
          python3.10 setup.py sdist bdist_wheel
          python3.10 -m auditwheel repair --plat manylinux_2_31_x86_64 dist/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-linux_x86_64.whl
      - name: run tests
        run: |
          ls ./wheelhouse
          python3.10 -m pip install ./wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-manylinux_2_31_x86_64.whl
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.10.so eos-debugger &
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.10.so python3.10 -m ipyeos -m pytest -s -x tests/test.py
      - name: release-pyeos
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp38-cp38-manylinux_2_31_x86_64.whl
            ./wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-manylinux_2_31_x86_64.whl
            ./wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-manylinux_2_31_x86_64.whl