name: build ipyeos manylinux

on:
  push:
    branches: [ debug ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-20.04
    # container:
    #   image: quay.io/pypa/manylinux2014_x86_64
    env:
      IPYEOS_VERSION: 0.2.14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Cache eos build
        uses: actions/cache@v2
        id: cache-leap-build
        with:
          key: leap-build-v2.1.0-manylinux-1
          path: leap/build
      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake curl git libboost-all-dev libgmp-dev libssl-dev llvm-11-dev
      - name: Build leap
        if: steps.cache-leap-build.outputs.cache-hit != 'true'
        working-directory: leap
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 ..
          make -j $(nproc)
      - name: pull manylinux2014_x86_64
        run: |
          docker pull quay.io/pypa/manylinux2014_x86_64
      - name: build wheel in container
        run: |
          docker run -it -v $(pwd):/root/dev -w /root/dev quay.io/pypa/manylinux2014_x86_64 ./scripts/build-wheel-linux.sh
      - name: run tests
        run: |
          ls ./dist/wheelhouse
          python3.9 -m pip install ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          python3.9 -m ipyeos -m pytest -s -x tests/test.py
      - name: release-pyeos
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            ./dist/wheelhouse/ipyeos-${{ env.IPYEOS_VERSION }}-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
