name: release ipyeos

on:
  push:
    branches: [ release ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      IPYEOS_VERSION: 0.4.7
    strategy:
      matrix:
        python-version: [3.9]
        os: ['ubuntu-20.04']
        # python-version: [3.9]
        # os: ['ubuntu-18.04']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest scikit-build cython auditwheel
          python setup.py sdist
      - name: Downloading whl files
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        working-directory: dist
        run: |
          python ../scripts/download.py ${{ env.IPYEOS_VERSION }}
      - name: Publish a Python distribution to PyPI
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the ipyeos Docker image
        run: |
          sleep 600
          docker build . --tag ghcr.io/uuosio/ipyeos:latest --tag ghcr.io/uuosio/ipyeos:v0.4.6
          docker push ghcr.io/uuosio/ipyeos:latest
          docker push ghcr.io/uuosio/ipyeos:v0.4.6
